---

title: Automations
icon: mdi:timer-outline
cards:
  - type: entities
    title: Motion
    show_header_toggle: false
    entities:
      - entity: switch.front_door_smart_motion_detection
  - type: entities
    title: Doors
    show_header_toggle: false
    entities:
      - entity: automation.announce_door_opened
      - entity: automation.announce_door_opened_event
      - entity: automation.announce_door_closed
      - entity: automation.announce_door_closed_event

