---
# https://www.home-assistant.io/integrations/binary_sensor

binary_sensor:
  # Service will return a json object with key "busy" and a boolean value.
  # Sensor value is set to the boolean value. If the service is not available,
  # it will return "unavailable".
  #
  # Example response: {"busy":false}
  - platform: rest
    resource: !secret teams_rest_url
    name: Teams on call
    value_template: "{{ value_json.busy }}"

