---
# https://www.home-assistant.io/integrations/statistics

sensor:
  - platform: statistics
    name: Guest Bathroom Humidity Average Over Last 24h
    entity_id: sensor.4_in_1_sensor_humidity
    state_characteristic: average_linear
    max_age:
      hours: 24

