---
# yamllint disable rule:line-length

- alias: Alarm - Triggered Armed Away
  id: alarm_triggered_armed_away
  triggers:
    - trigger: state
      entity_id: alarm_control_panel.alarm
      to: triggered
  conditions: []
  actions:
    - action: notify.mobile_apps
      data:
        title: Alarm Triggered!
        message: The alarm was triggered
        data:
          group: alarm
          notification_icon: mdi:shield-home-outline
          ttl: 0
          priority: high

- alias: Alarm - Away Door Alarm
  id: alarm_away_door_alarm
  triggers:
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_2
      to: "on"
      variables:
        location_name: Kitchen
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open
      to: "on"
      variables:
        location_name: Front
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
      to: "on"
      variables:
        location_name: Laundry
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_3
      to: "on"
      variables:
        location_name: Office
  conditions:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  actions:
    - action: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm
    - action: notify.mobile_apps
      data:
        title: Door Alarm Triggered!
        message: "{{ location_name }} Door Alarm Triggered!"
        data:
          group: alarm
          notification_icon: mdi:shield-home-outline
          ttl: 0
          priority: high
    - action: notify.email
      data_template:
        title: Door Alarm Triggered
        message: "{{ location_name }} door alarm triggered!"

