---
# yamllint disable rule:line-length
- alias: Announce Door Opened
  id: announce_door_opened
  triggers:
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_window_door_is_open_3
      to: "on"
      variables:
        location_name: Kitchen
    #- trigger: state
    #  entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open
    #  to: "on"
    #  variables:
    #    location_name: Front
    #- trigger: state
    #  entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
    #  to: "on"
    #  variables:
    #    location_name: Laundry
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_window_door_is_open
      to: "on"
      variables:
        location_name: Office
  mode: queued
  conditions:
    - condition: state
      entity_id: binary_sensor.halloween_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.thanksgiving_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.christmas_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.today_is_someones_birthday
      state: "off"
  actions:
    action: script.sonos_say
    data:
      message: "{{ location_name }} door open"
      delay: "00:00:03"

- alias: Announce Door Closed
  id: announce_door_closed
  triggers:
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_window_door_is_open_3
      to: "off"
      variables:
        location_name: Kitchen
    #- trigger: state
    #  entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open
    #  to: "off"
    #  variables:
    #    location_name: Front
    #- trigger: state
    #  entity_id: binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
    #  to: "off"
    #  variables:
    #    location_name: Laundry
    - trigger: state
      entity_id: binary_sensor.z_wave_door_window_sensor_window_door_is_open
      to: "off"
      variables:
        location_name: Office
  mode: queued
  conditions:
    - condition: state
      entity_id: binary_sensor.halloween_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.thanksgiving_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.christmas_month
      state: "off"
    - condition: state
      entity_id: binary_sensor.today_is_someones_birthday
      state: "off"
  actions:
    action: script.sonos_say
    data:
      message: "{{ location_name }} door closed"
      delay: "00:00:03"

- alias: Announce Door Opened (Event)
  id: announce_door_opened_event
  triggers:
    trigger: state
    entity_id:
      - binary_sensor.z_wave_door_window_sensor_window_door_is_open
      #- binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_2
      - binary_sensor.z_wave_door_window_sensor_window_door_is_open_3
      #- binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
    to: "on"
  mode: queued
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.today_is_someones_birthday
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/birthday01.mp3
                delay: "00:00:16"
        - conditions:
            - condition: state
              entity_id: binary_sensor.halloween_month
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/ghost01.mp3
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.thanksgiving_month
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/turkey01.mp3
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.christmas_month
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/christmas01.mp3
                delay: "00:00:08"

- alias: Announce Door Closed (Event)
  id: announce_door_closed_event
  triggers:
    trigger: state
    entity_id:
      - binary_sensor.z_wave_door_window_sensor_window_door_is_open
      #- binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_2
      - binary_sensor.z_wave_door_window_sensor_window_door_is_open_3
      #- binary_sensor.z_wave_door_window_sensor_access_control_window_door_is_open_4
    to: "off"
  mode: queued
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.today_is_someones_birthday
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/birthday01.mp3
                delay: "00:00:16"
        - conditions:
            - condition: state
              entity_id: binary_sensor.halloween_month
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/howl01.mp3
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.thanksgiving_month
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/turkey01.mp3
                delay: "00:00:08"
        - conditions:
            - condition: state
              entity_id: binary_sensor.christmas_month
              state: "on"
          sequence:
            - action: script.sonos_play_file
              data:
                audio_url: audio/christmas01.mp3
                delay: "00:00:08"

