---

- alias: Turn Off Air Purifier Weekdays
  id: turn_off_air_purifier_weekdays
  triggers:
    trigger: time
    at: "07:00:00"
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  actions:
    action: script.air_purifier

- alias: Turn Off Air Purifier Weekends
  id: turn_off_air_purifier_weekends
  triggers:
    trigger: time
    at: "09:00:00"
  conditions:
    - condition: time
      weekday:
        - sat
        - sun
  actions:
    action: script.air_purifier

# Not considering motion, it's assumed if the shower is running.
- alias: Turn On Guest Bathroom Fan When Someone's Showering
  id: turn_on_guest_bathroom_fan_when_someones_showering
  triggers:
    - trigger: state
      entity_id: binary_sensor.someone_is_showering_in_guest_bathroom
      to: "on"
      for: "00:01:00"
  conditions:
    - condition: state
      entity_id: switch.dimmer_dry_contact_relay
      state: "off"
  actions:
    - action: switch.turn_on
      entity_id: switch.dimmer_dry_contact_relay

- alias: Motion - Turn Off Guest Bathroom Fan When No Motion Detected
  id: motion_turn_off_guest_bathroom_fan_when_no_motion_detected
  triggers:
    - trigger: state
      entity_id: binary_sensor.4_in_1_sensor_motion_detection
      from: "on"
      to: "off"
      for: "00:05:00"
  conditions:
    - condition: state
      entity_id: switch.double_switch_1
      state: "on"
  actions:
    - action: switch.turn_off
      entity_id: switch.double_switch_1

- alias: Turn Off Main Bathroom Fan After Period Of Time
  id: turn_off_main_bathroom_fan_after_period_of_time
  description: >
    Turn off the fan if it's been on for 20 minutes. There isn't motion
    detection available.
  triggers:
    - trigger: state
      entity_id: switch.double_switch_1_2
      to: "on"
      for: "00:20:00"
  conditions: []
  actions:
    - action: switch.turn_off
      entity_id: switch.double_switch_1_2

