---
- alias: Turn Off Air Purifier Weekdays (6:30am)
  id: turn_off_air_purifier_weekdays
  triggers:
    trigger: time
    at: "06:30:00"
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  actions:
    action: script.air_purifier

- alias: Turn Off Air Purifier Weekends (9:00am)
  id: turn_off_air_purifier_weekends
  triggers:
    trigger: time
    at: "09:00:00"
  conditions:
    - condition: time
      weekday:
        - sat
        - sun
  actions:
    action: script.air_purifier

