---
- alias: Turn Off Air Purifier Weekdays (6:30am)
  id: turn_off_air_purifier_weekdays
  triggers:
    trigger: time
    at: "06:30:00"
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  actions:
    action: switch.turn_off
    data:
      entity_id: switch.wemo_mini

- alias: Turn Off Air Purifier Weekends (7:15am)
  id: turn_off_air_purifier_weekends
  triggers:
    trigger: time
    at: "07:15:00"
  conditions:
    - condition: time
      weekday:
        - sat
        - sun
  actions:
    action: switch.turn_off
    data:
      entity_id: switch.wemo_mini

- alias: Turn On Air Purifier Mid-Morning
  id: turn_on_air_purifier_midmorning
  triggers:
    trigger: time
    at: "07:20:00"
  actions:
    action: switch.turn_on
    data:
      entity_id: switch.wemo_mini

