---

- alias: Turn on Lights to Wake Us Up
  id: turn_on_light_to_wake_us_up
  description: >-
    Fade lights in on weekday mornings to simulate a sunrise next to
    our faces to wake us up.
  initial_state: true
  triggers:
    trigger: time
    at: "06:20:00"
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  actions:
    action: light.turn_on
    data:
      entity_id: light.hue_white_lamp_1
      brightness: 255
      transition: 1800

- alias: Turn Off Lights Before Work
  id: turn_off_lights_before_work
  description: >-
    Turn off lights weekday mornings after sunrise.
  initial_state: true
  triggers:
    - trigger: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 6.0
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  actions:
    action: light.turn_off
    entity_id: light.hue_white_lamp_1

- alias: Turn On Lights Before Sunset
  description: >-
    Gradually fade in lights as the sun sets into the night.
  initial_state: true
  triggers:
    trigger: sun
    event: sunset
    offset: "-1:15:00"
  actions:
    action: light.turn_on
    data:
      entity_id:
        - light.hue_white_lamp_1
        - light.hue_white_lamp_2
      brightness: 255
      transition: 1500

# Hue bulbs take 30 minutes to fade to off.
- alias: Turn Off Lee's Bedside at Night
  initial_state: true
  triggers:
    trigger: time
    at: "20:00:00"
  actions:
    action: light.turn_off
    data:
      entity_id: light.hue_white_lamp_2
      transition: 1800

# Hue bulbs take 30 minutes to fade to off.
- alias: Turn Off Andrei's Bedside By 9:00pm
  id: turn_off_andrei_s_bedside_by_9_00pm
  triggers:
    trigger: time
    at: "20:30:00"
  actions:
    action: light.turn_off
    data:
      entity_id: light.hue_white_lamp_1
      transition: 1800

- alias: Turn On Night-Light at Sunset
  id: turn_on_night_light_at_sunset
  initial_state: true
  triggers:
    trigger: sun
    event: sunset
    offset: "-0:30:00"
  actions:
    action: light.turn_on
    data:
      entity_id: light.controller_rgb_44_key_ir_cde6d9
      brightness: 13

- alias: Turn Off Night-Light After Sunrise
  id: turn_off_night_light_after_sunrise
  description: Turn off night-light 15 minutes after sunrise.
  initial_state: true
  triggers:
    trigger: sun
    event: sunrise
    offset: "00:15:00"
  actions:
    action: light.turn_off
    data:
      entity_id: light.controller_rgb_44_key_ir_cde6d9

- alias: Turn On Dining Room Lamp Before Sunset
  initial_state: true
  triggers:
    trigger: sun
    event: sunset
    offset: "-1:00:00"
  actions:
    action: switch.turn_on
    data:
      entity_id: switch.tp_link_smart_plug_ac23

- alias: Turn Off Dining Room Lamp
  initial_state: true
  triggers:
    trigger: time
    at: "22:30:00"
  actions:
    action: switch.turn_off
    data:
      entity_id: switch.tp_link_smart_plug_ac23

- alias: Toggle Live Sign When Busy in Teams
  triggers:
    trigger: state
    entity_id: binary_sensor.teams_on_call
  actions:
    - action: switch.turn_{{ trigger.to_state.state }}
      target:
        entity_id: switch.tp_link_smart_plug_d6d2

- alias: Turn On Both Living Room Bookshelf Lamps From Single Switch
  id: turn_on_both_living_room_bookshelf_lamps_from_single_switch
  description: >-
    Physically toggling the one reachable switch should toggle the other switch
    in tandem
  triggers:
    - trigger: state
      entity_id: switch.tp_link_smart_plug_ac7b
  actions:
    - action: switch.turn_{{ trigger.to_state.state }}
      target:
        entity_id: switch.tp_link_smart_plug_1106

