---
- alias: Turn On Night-Light at Sunset
  id: turn_on_night_light_at_sunset
  initial_state: true
  triggers:
    trigger: sun
    event: sunset
    offset: "-0:30:00"
  actions:
    action: light.turn_on
    data:
      entity_id: light.controller_rgb_44_key_ir_cde6d9
      brightness: 13

- alias: Turn Off Night-Light After Sunrise
  id: turn_off_night_light_after_sunrise
  description: Turn off night-light 15 minutes after sunrise.
  initial_state: true
  triggers:
    trigger: sun
    event: sunrise
    offset: "00:15:00"
  actions:
    action: light.turn_off
    data:
      entity_id: light.controller_rgb_44_key_ir_cde6d9

- alias: Turn On Dining Room Lamp Before Sunset
  initial_state: true
  triggers:
    trigger: sun
    event: sunset
    offset: "-1:00:00"
  actions:
    action: switch.turn_on
    data:
      entity_id: switch.wemo_mini_1

- alias: Turn Off Dining Room Lamp
  initial_state: true
  triggers:
    trigger: time
    at: "22:30:00"
  actions:
    action: switch.turn_off
    data:
      entity_id: switch.wemo_mini_1

- alias: Toggle Live Sign When Busy in Teams
  triggers:
    trigger: state
    entity_id: binary_sensor.teams_on_call
  actions:
    - action: switch.turn_{{ trigger.to_state.state }}
      target:
        entity_id: switch.wemo_mini_4

