---
- alias: Laundry flooding
  id: laundry_flooding
  triggers:
    trigger: state
    entity_id: binary_sensor.flood_sensor_water_leak_state
    from: "off"
    to: "on"
    for: "00:00:15"
  actions:
    - action: notify.email
      data_template:
        title: Laundry room is flooding
        message: You should probably check it out.
    - action: script.sonos_say
      data:
        message: >-
          Crikey!
          We've sprunga leak in the laundry room!
          I said crikey!
          We've sprunga leak in the laundry room!
        delay: "00:00:15"
    - action: notify.mobile_apps
      data:
        message: The laundry room is flooding

- alias: Low Battery Notification
  id: low_battery_notification
  description: Notify of low battery level in devices which have batteries.
  mode: parallel
  triggers:
    # The default trigger is to wait for the "low battery level" sensor to
    # flip for a period of time however this approach isn't very reliable.
    # Most of the devices will lose connectivity well before this sensor
    # flips. Ideally, and in time, each of the unique behavior of the devices
    # is identified and handled with a its own trigger.
    - trigger: state
      entity_id:
        - binary_sensor.flood_sensor_low_battery_level
        - binary_sensor.z_wave_door_window_sensor_low_battery_level
        - binary_sensor.z_wave_door_window_sensor_low_battery_level_2
        - binary_sensor.z_wave_door_window_sensor_low_battery_level_4
        - binary_sensor.z_wave_door_window_sensor_low_battery_level_5
      from: "off"
      to: "on"
      for:
        hours: 1

    # After it's been on 10% for a few days it'll slowly become more and more
    # unresponsive until it completely loses connectivity. Never reports lower
    # than 10%.
    - trigger: numeric_state
      entity_id:
        - sensor.4_in_1_sensor_battery_level
      below: 11
      for:
        hours: 8

    # Smoke alarms will start chirping the minute they reach 77% battery
    # level. They will stay at 78% for several days however. Send notification
    # just before they drop to 77%. Would prefer to trigger only if it's been
    # at 77% for a few days however restarting Home Assistant will reset that
    # lookup. Using a more conservative value instead.
    - trigger: numeric_state
      entity_id:
        - sensor.zcombo_g_smoke_co_alarm_battery_level
        - sensor.zcombo_g_smoke_co_alarm_battery_level_2
        - sensor.zcombo_g_smoke_co_alarm_battery_level_3
      below: 79
      for:
        hours: 8

    - trigger: numeric_state
      entity_id:
        - sensor.hue_smart_button_1_battery
      below: 15
      for:
        hours: 8
  actions:
    - action: notify.mobile_apps
      data:
        message: The {{ trigger.to_state.attributes.friendly_name }} is Low
        data:
          tag: bettery
          group: battery
    - action: notify.email
      data_template:
        title: Low Battery Detected
        message: >-
          The {{ trigger.to_state.attributes.friendly_name }} is low.
          You should probably check it out.

# Designed to interrupt any automations that slowly fade the light on/off.
# If button is pressed during an automation that is fading it on, the light
# will turn off completely, and vice versa.
- alias: Bedroom Button Pressed
  id: bedroom_button_pressed
  triggers:
    - trigger: state
      entity_id: event.hue_smart_button_1_button_1
      attribute: event_type
      to:
        - long_press
        - long_release
        - short_release
  mode: queued
  actions:
    - if:
        - alias: Light is on, any brightness
          condition: state
          entity_id: light.hue_white_lamp_3
          state: "on"
      then:
        - alias: Turn it off
          action: light.turn_off
          target:
            entity_id: light.hue_white_lamp_3
      else:
        - action: light.turn_on
          data:
            entity_id: light.hue_white_lamp_3
            # Specify brightness to override any previous brightness less than
            # full. Button could've been pressed before when light was fading
            # on, don't want to restore that previous dim light.
            brightness: 255

