---
- alias: Low Battery Notification
  id: low_battery_notification
  description: Notify of low battery level in devices which have batteries.
  triggers:
    - trigger: state
      entity_id:
        # Sensor fires at 80% battery level remaining then device is mostly
        # off the network and otherwise unresponsive.
        #- binary_sensor.4_in_1_sensor_low_battery_level
        #- binary_sensor.flood_sensor_low_battery_level
        - binary_sensor.z_wave_door_window_sensor_low_battery_level
        - binary_sensor.z_wave_door_window_sensor_low_battery_level_2
        #- binary_sensor.z_wave_door_window_sensor_low_battery_level_3
        #- binary_sensor.z_wave_door_window_sensor_low_battery_level_4
        #- binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level
        #- binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level_2
        #- binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level_3
      from: "off"
      to: "on"
      for: "01:00:00"
    # Smoke alarms will start chirping the minute they reach 77% battery
    # level. They will stay at 78% for several days however. Send notification
    # just before they drop to 77%. Would prefer to trigger only if it's been
    # at 77% for a few days however restarting Home Assistant will reset that
    # lookup. Using a more conservative value instead.
    #- trigger: numeric_state
    #  entity_id:
    #    - sensor.zcombo_g_smoke_co_alarm_battery_level
    #    - sensor.zcombo_g_smoke_co_alarm_battery_level_2
    #    - sensor.zcombo_g_smoke_co_alarm_battery_level_3
    #  below: 78
    #  for: "08:00:00"
  actions:
    #- action: notify.mobile_apps
    #  data:
    #    message: The {{ trigger.to_state.attributes.friendly_name }} is Low
    #    data:
    #      tag: bettery
    #      group: battery
    - action: notify.email
      data_template:
        title: Low Battery Detected
        message: >-
          The {{ trigger.to_state.attributes.friendly_name }} is low.
          You should probably check it out.

