---

- alias: System - Clean Up Camera Snapshots Directory Periodically
  id: system_clean_up_camera_snapshots_directory_periodically
  description: >
    Daily delete of all camera shapshots files older than 3 days.
  triggers:
    - trigger: time
      at: "05:27:18"
  actions:
    - action: shell_command.clean_camera_snapshots
      data:
        days_threshold: 3

